### ISSUE TITLE
Recommendation: python env

### ISSUE THREAD

**Issue by mattaereal** [renatahodovan/grammarinator#10]
EDIT: The documentation explicitly says python3, my mistake to run simple ```python setup.py install``` on my guest OS without realizing by default uses python2 and that's why I had syntax errors.

You can always add a shebang ```#!/usr/bin/env python3``` to avoid this, but in this case it was my mistake.

Thanks for your projects and keep up the good work.

**Comment by renatahodovan** [comment]
@mattaereal Thanks for reporting the imprecision of the readme, it is updated. And also thanks for the positive feedback!
