### ISSUE TITLE
API usage

### ISSUE THREAD

**Issue by bendrissou** [renatahodovan/grammarinator#105]
I would like to know how to invoke `grammarinator-generate` from a Python script. Instead of CLI.

Are there any documentations or examples please?

**Comment by renatahodovan** [comment]
Hi @bendrissou !

[grammarinator-generate](https://grammarinator.readthedocs.io/en/latest/guide/test_generation.html) is basically a CLI wrapper utilizing the [GeneratorTool](https://grammarinator.readthedocs.io/en/latest/grammarinator.tool.html#grammarinator.tool.GeneratorTool) module. If you would like to invoke grammarinator-generate from a Python script, then you can do it as with any other executable, e.g., with using [subprocess.run](https://docs.python.org/3/library/subprocess.html#subprocess.run).

However, if your goal is to avoid starting a subprocess and use Grammarinator from API (as the title suggests) then you should setup and instantiate [GeneratorTool](https://grammarinator.readthedocs.io/en/latest/grammarinator.tool.html#grammarinator.tool.GeneratorTool) yourself and iteratively call its [create](https://github.com/renatahodovan/grammarinator/blob/master/grammarinator/tool/generator.py#L155) method, just like the CLI implementation does [here](https://github.com/renatahodovan/grammarinator/blob/master/grammarinator/generate.py#L63) and [here](https://github.com/renatahodovan/grammarinator/blob/master/grammarinator/generate.py#L83).

**Comment by bendrissou** [comment]
Great! 

Thank you for your clear answer.
