### ISSUE TITLE
[question] Evolutionary options

### ISSUE THREAD

**Issue by igor-simoes** [renatahodovan/grammarinator#11]
Hi Renata,

Last days I was running grammarinator with a JS grammar and works perfectly, thanks. Looking the last commits, I saw that there is an evolutionary settings to generate files through existents files. I tried to run it with "--population" args but the tool didn't recognize it.
There is any wiki, paper or something to explain how it works?

thanks

**Comment by renatahodovan** [comment]
Hi Igor,

What do you mean by `--population` arg isn't recognized? Could you paste the command you used, please?
(As a population argument you should give a path to a directory containing serialized tree representations, created previously with the `grammarinator-parse` tool.)
As for the paper and the documentation, both of them are in progress, hopefully they will be published soon.
