### ISSUE TITLE
Test generation failed: name 'local_ctx' is not defined.

### ISSUE THREAD

**Issue by matthewbdwyer** [renatahodovan/grammarinator#12]
Hi,

Grammarinator looks very nice and I plan to use it in a compiler course I am developing so that everyone learns about grammar-based fuzzing.

Given a simple grammar without actions (see below), running these two commands:

$ grammarinator-process ../antlr4/Kal.g4 --no-actions
$ grammarinator-generate -l KalUnlexer.py -p KalUnparser.py

which yields:

Test generation failed: name 'local_ctx' is not defined.

I'm using grammarinator 18.10 on Ubuntu 18.04

Thanks for developing this tool and for any help you can provide.

matt
-----------------------------------------------------------------------------------------------------------
grammar Kal;

// program is a sequence of decls and definitions with one top level expr
program : (extern_decl | function)* expr
;

extern_decl : 'extern' prototype
;

prototype : ID '(' proto_args ')'
;

proto_args : ID (',' ID) *
;

function : 'def' prototype expr
;

//
// operator precedence in ANTLR4 comes from ordering
//
// # creates a named alternative that can be accessed in visitor
//
// factoring out binary expressions (which is nice for visitors)
// leads to mutual left recursive rules which ANTLR4 doesn't handle
//
expr : SUB expr                                 #unaryMinusExpr
     | expr op=(MUL | DIV) expr                 #multiplicativeExpr
     | expr op=(ADD | SUB) expr                 #additiveExpr
     | expr op=(LT | LTE | GT | GTE) expr       #relationalExpr
     | expr op=(EQ | NE) expr                   #equalityExpr
     | atom                                     #atomExpr
;

atom : ite              #iteExpr
     | call             #callExpr
     | '(' expr ')'     #parenExpr
     | NUM              #numExpr
     | ID               #idExpr
;

ite : 'if' expr 'then' expr 'else' expr
;

call : ID '(' call_args ')'
;

call_args : expr (',' expr)*
;

// Lexer

MUL : '*' ;
DIV : '/' ;
ADD : '+' ;
SUB : '-' ;
LT  : '<' ;
LTE : '<=' ;
GT  : '>' ;
GTE : '>=' ;
EQ  : '==' ;
NE  : '!=' ;

NUM : [0-9]+ ;

ID : [a-zA-Z_][a-zA-Z0-9_]* ;

// "-> skip" defines a lexical action which skips the matched characters

WS : [ \t\n]+ -> skip ;

COMMENT : '#' ~[\n]* -> skip ;

**Comment by renatahodovan** [comment]
Thanks for the report and the kind words. It seems that variables inside labeled alternations were not handled correctly, but now it's fixed in the latest master.

Note: since your grammar is recursive you probably want to set a maximum generation depth (`-d <NUM>`) to avoid too deep recursions (or too big tests).
