### ISSUE TITLE
Random seed initialisation not working

### ISSUE THREAD

**Issue by bendrissou** [renatahodovan/grammarinator#170]
When mutation and recombination modes are enabled, `grammarinator-generate` doesn't generate the same output consistently, despite setting `--random-seed` to a fixed number.

Here is the example command I am using:

```
grammarinator-generate JSONGenerator.JSONGenerator -r json -o tests/input.in -d 60 -n 1 --random-seed 4 --sys-path . -j=1 --population ../seeds/grts --no-generate
```

I used a JSON grammar to build `JSONGenerator`.

**Comment by renatahodovan** [comment]
@bendrissou Thanks for the report. The issue is solved on the latest master, but you need to regenerate your existing corpus to have the expected behaviour. Please check it and tell me if it's working for you.
