### ISSUE TITLE
How to generate only printable words

### ISSUE THREAD

**Issue by 1wc** [renatahodovan/grammarinator#19]
Hello, I run the example case for HTML and generated 100 HTMLs, but many labels had unprintable words, what should I do if I only want to generate printable words in labels, thanks!

**Comment by renatahodovan** [comment]
Hi @1wc! I'm not sure that I understand what you mean under labels and words (my guess is that they should be rules and tokens). Anyhow, if you would like to generate printable characters only, then you should set the `dot` option to `any_ascii_char` or `any_ascii_letter` [here](https://github.com/renatahodovan/grammarinator/blob/master/examples/grammars/HTMLParser.g4#L36) and regenerate the fuzzer.

**Comment by 1wc** [comment]
Ha ha, thank you very much. I meant the generated HTML tags(labels) had many unprintable characters(words), so your answer worked for me perfectly.

**Comment by renatahodovan** [comment]
I'm glad to hear that it works :)

**Comment by akosthekiss** [comment]
@1wc FYI: you may be interested in the new command line option of grammarinator-process. With `-D`, you may set/override options that can be specified in the grammar's options block. This allows experimenting without changing the grammar. In your case, `grammarinator-process -Ddot=any_ascii_letter ...` should work, for example.

P.S.: This new feature was actually triggered by this issue of yours, so, thanks!
