### ISSUE TITLE
Exclude tests directory from installation

### ISSUE THREAD

**Issue by D3vil0p3r** [renatahodovan/grammarinator#209]
The install of grammarinator generates `/usr/lib/python3.11/site-packages/tests/__init__.py` that creates conflicts with other Python packages that install `tests` directory (and that need to be fixed too).

It is needed also according to [Python package guidelines](https://wiki.archlinux.org/title/Python_package_guidelines#Test_directory_in_site-package).

Can you please exclude `tests` in your `pyproject.toml` file?

Give a look to https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html and search for `exclude` keyword.

**Comment by akosthekiss** [comment]
@D3vil0p3r Thanks for reporting the issue. Hopefully fixed now. Could you please confirm whether the original issue is resolved?

**Comment by D3vil0p3r** [comment]
It is. Thank you.

> @D3vil0p3r Thanks for reporting the issue. Hopefully fixed now. Could you please confirm whether the original issue is resolved?
