### ISSUE TITLE
Try to get C/Cpp Generator work

### ISSUE THREAD

**Issue by Hanseltu** [renatahodovan/grammarinator#21]
Hi, thanks for your awesome tool!

I am wondering how grammarianor deals with the C/Cpp antlr-v4 file.  Specifically, [CPP.14.g4](https://github.com/antlr/grammars-v4/blob/master/cpp/CPP14.g4) is not separated into Lexer and Parser. Is grammarinator can also work ok in this situation? How can I get test cases from a single CPP14.g4 file?

Any suggestions are welcome, thank you very much!

**Comment by akosthekiss** [comment]
@Hanseltu Grammarinator can work both with lexer/parser and combined grammars. So, having CPP14.g4 in a single file makes no problem for the tool. E.g., you could just use:
```sh
grammarinator-process --no-actions -o fuzzer CPP14.g4 
grammarinator-generate CPP14Generator.CPP14Generator --sys-path fuzzer -o tests/test_%d.cpp \
    -d 20 --serializer grammarinator.runtime.simple_space_serializer
```

Some notes:
- The grammar in the ANTLR repo contains actions with inlined Java code. Such actions would end up in the generated code, which is a) for generation not parsing and b) Python code not Java, so it would break things. Thus, `--no-actions` of `grammarinator-process` gets rid of that.
- I had to edit the grammar as it uses two rules that break in Python context: `True` and `False`. I had to rename them, I've simply added an underscore to their names. (Lines 1248, 1388, 1886, and 1887.)
- The call of `grammarinator-generate` uses `--serializer grammarinator.runtime.simple_space_serializer` to ensure that language elements are separated. This is a very simple serializer, uses a single space everywhere and so generates test cases consisting of a single line. If you need pretty printed tests, you should either post-process the tests or write your own serializer.
- The example generates a single test case. If you need more, use `-n N`.
- The example limits the size of the generated test(s) to trees (rule derivations) of depth 20. Feel free to experiment with other settings.

**Comment by Hanseltu** [comment]
@akosthekiss Thanks for your nice guide! I can handle this situation now.
