### ISSUE TITLE
Unlexer generates forbidden characters

### ISSUE THREAD

**Issue by abyss7** [renatahodovan/grammarinator#23]
Versions of packages:

    ➤ pip install --user grammarinator                                                                     
    Requirement already satisfied: grammarinator in /home/user/.local/lib/python3.8/site-packages (19.3)
    Requirement already satisfied: antlerinator==4.7.1-1 in /home/user/.local/lib/python3.8/site-packages (from grammarinator) (4.7.1.post1)
    Requirement already satisfied: autopep8 in /home/user/.local/lib/python3.8/site-packages (from grammarinator) (1.5.4)
    Requirement already satisfied: antlr4-python3-runtime==4.7.1 in /home/user/.local/lib/python3.8/site-packages (from antlerinator==4.7.1-1->grammarinator) (4.7.1)
    Requirement already satisfied: pycodestyle>=2.6.0 in /home/user/.local/lib/python3.8/site-packages (from autopep8->grammarinator) (2.6.0)
    Requirement already satisfied: toml in /home/user/.local/lib/python3.8/site-packages (from autopep8->grammarinator) (0.10.1)

I have lexer rules:

    STRING_LITERAL: QUOTE_SINGLE ( ~([\\']) | (BACKSLASH .) )* QUOTE_SINGLE;
    BACKSLASH: '\\';
    QUOTE_SINGLE: '\'';

And a parser rule (one of alternatives):

    TRIM LPAREN (BOTH | LEADING | TRAILING) STRING_LITERAL FROM columnExpr RPAREN

I run generator like this:

    grammarinator-generate -r queryList -o /tmp/sql_test_%d.sql -n 100 -c 0.3 -d 20 -p Unparser.py -l Unlexer.py --test-transformers SpaceTransformer.single_line_whitespace

And sometimes get the following output (partial):

    tRIM	( bOTH '''	FrOM	(	*

I don't understand why there are triple single-quotes here. Looks like a bug.

**Comment by abyss7** [comment]
I tried the following to debug an issue:

    list(chain(*multirange_diff([(0, 10)], [(1, 2), (3, 4)])))
    [0, 1, 2, 3, 4, 10]

Looks like it's not an expected result, since the unlexer then just does `random.choice` from similarly generated list.

**Comment by akosthekiss** [comment]
Hi @abyss7,

Thanks for reporting this issue. It's been known for some time that there is something off around `multirange_diff`. However, we have seen it as a sub-optimality only, not as a source of bug, until now.

We have a bigger rework of charset handling, lingering around for some months now, that hasn't been released yet because of the above. But now that it is proven to cause problems, we shall land it soon.

**Comment by akosthekiss** [comment]
@abyss7 The charset rework has landed. Could you try and see whether it solves your issue?

**Comment by akosthekiss** [comment]
Closing this issue as almost a year has passed since the original report (and the bug is most probably fixed). However, if the problem still stands, feel free to re-open this issue (or open a new one).
