### ISSUE TITLE
'poetry build' error

### ISSUE THREAD

**Issue by noptrix** [renatahodovan/grammarinator#39]
Hi @renatahodovan!

I'm facing the following error when trying to run `poetry build` in the root dir of `grammarinator`:

```
==> Starting build()...

  PyProjectException

  [tool.poetry] section not found in /home/noptrix/blackarch/repos/blackarch/packages/grammarinator/src/grammarinator/pyproject.toml

  at /usr/lib/python3.10/site-packages/poetry/core/pyproject/toml.py:56 in poetry_config
      52│     def poetry_config(self):  # type: () -> Optional[TOMLDocument]
      53│         if self._poetry_config is None:
      54│             self._poetry_config = self.data.get("tool", {}).get("poetry")
      55│             if self._poetry_config is None:
    → 56│                 raise PyProjectException(
      57│                     "[tool.poetry] section not found in {}".format(self._file)
      58│                 )
      59│         return self._poetry_config
      60│ 
==> ERROR: A failure occurred in build().
    Aborting...
```
Any ideas here? Here is the [PKGBUILD](https://github.com/BlackArch/blackarch/blob/f5804a13e99b08102aa19f2c9b739bc32e5171f6/packages/grammarinator/PKGBUILD) to build `grammarinator` under ArchLinux.

**Comment by renatahodovan** [comment]
Hi @noptrix !

Thanks for the report! The reason of the error is that Grammarinator is not prepared for poetry builds. Technically, the pyproject.toml file lacks of the `[tool.poetry]` section. I'm not familiar with poetry yet, but if I'm not wrong, it's used to create a dist package. If this is the case, then why don't you use python build to do the same? [Link](https://packaging.python.org/en/latest/tutorials/packaging-projects/#generating-distribution-archives)


In this case, you should replace `poetry build` with `python3 -m build` (and maybe another command to ensure that PyPA build is installed: `python3 -m pip install --upgrade build`)

Cheers,
Reni

**Comment by noptrix** [comment]
ACK. will try via PyPA. thank you!
