### ISSUE TITLE
Does the grammar need to be targeted to Python?

### ISSUE THREAD

**Issue by marcospassos** [renatahodovan/grammarinator#4]
It's clear in the documentation if the grammar must be written in Python. Our grammar uses semantic predicates (is it supported, right?), so we're getting errors for generating the tests.

**Comment by renatahodovan** [comment]
@marcospassos Yes, currently we only support Python target and hence the semantic predicates must be written in Python. What kind of errors do you get? Could you provide a minimal example of the grammar causing the issue?

**Comment by marcospassos** [comment]
Just errors related to invalid syntax, once the generated parser was trying to interpret Java as Python :)

Thank you again!

**Comment by marcospassos** [comment]
Btw, perhaps it should be documented just to make it more clear for other devs :)
