### ISSUE TITLE
How to keep spaces as part of the generated tests?

### ISSUE THREAD

**Issue by marcospassos** [renatahodovan/grammarinator#7]
Is there any way to keep the spaces in the output? In our tests, it's generating invalid expressions.

We noticed in the example a space transformer, but we could not understand how to use it for our case.

**Comment by marcospassos** [comment]
We managed to change the transformer for including spaces as part of the generated tests. Thank you!

**Comment by docfate111** [comment]
What is a transformer? I'm running into the same problem. How did you fix it?
