### ISSUE TITLE
Generation seed not working

### ISSUE THREAD

**Issue by bendrissou** [renatahodovan/grammarinator#95]
I am trying to use option `--random-seed` in order to be able to generate the same input when given the same seed number.

However, it's not working, as the generated inputs differ.

I have experimented with multiple grammars, including the json antlr grammar. The following is the command I am using:

```
grammarinator-generate JSONGenerator.JSONGenerator -r json -o tests/test_1.json -n 1 --random-seed 22 --sys-path .
```

The versions I tried:
```
grammarinator-generate 19.3.post125+geecdcb7
grammarinator-generate 19.3.post136+g350ce45
```

**Comment by renatahodovan** [comment]
Generating with fixed seed is only supported in single process mode for now (as the help message of `--random-seed` mentions). To switch to single process mode, you should add the `-j=1` argument to your command.

However, this means performance loss ofc... I'll look into how support seeds across multiple processes.
